metrovote/config/routes.rb
Metrovote::Application.routes.draw do

  namespace :admin do
    resources :elections do
      resources :positions do
        resources :candidates
      end
    end
  end

  resources :elections do
    resources :positions do
      resources :candidates
    end
  end

  resources :positions do
    member do
      get 'compare'
    end
  end

  match 'candidates/facebook', :to => 'candidates#facebook'
  match 'candidates/contact-info', :to => 'candidates#contact_info'

  match 'admin', :to => 'admin/elections#index'

  resources :candidates

  root :to => 'positions#index'

end

metrovote/app/models/election.rb
class Election < ActiveRecord::Base
  has_many :positions

  def candidate_ids
    ids = []
    self.positions.each do |position|
      position.candidates.each do |candidate|
        ids.push(candidate.id)
      end
    end
    return ids
  end

  def article_sources
    ids = self.candidate_ids.join(", ").gsub(/(\d+)/,"'\\1'")
    Article.find_by_sql "select source,host,count(source) as count from articles where candidate_id IN (#{ids}) group by source"
  end
end

metrovote/app/controllers/admin/elections_controller.rb
class Admin::ElectionsController < ElectionsController
  # GET /elections
  # GET /elections.xml
  def index
    @elections = Election.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @elections }
    end
  end
  #
  # GET /admin/elections/new
  # GET /admin/elections/new.xml
  def new
    @election = Election.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @election }
    end
  end

  # GET /admin/elections/1/edit
  def edit
    @election = Election.find(params[:id])
  end

  # POST /admin/elections
  # POST /admin/elections.xml
  def create
    @election = Election.new(params[:election])

    respond_to do |format|
      if @election.save
        format.html { redirect_to(admin_election_path(@election), :notice => 'Election was successfully created.') }
        format.xml  { render :xml => @election, :status => :created, :location => @election }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @election.errors, :status => :unprocessable_entity }
      end
    end
  end


end

metrovote/app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  # GET /elections
  # GET /elections.xml
  def index
    @elections = Election.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @elections }
    end
  end

  # GET /elections/1
  # GET /elections/1.xml
  def show
    @election = Election.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @election }
    end
  end

  # GET /elections/new
  # GET /elections/new.xml
  def new
    @election = Election.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @election }
    end
  end

  # GET /elections/1/edit
  def edit
    @election = Election.find(params[:id])
  end

  # POST /elections
  # POST /elections.xml
  def create
    @election = Election.new(params[:election])

    respond_to do |format|
      if @election.save
        format.html { redirect_to([:admin,@election], :notice => 'Election was successfully created.') }
        format.xml  { render :xml => @election, :status => :created, :location => @election }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @election.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /elections/1
  # PUT /elections/1.xml
  def update
    @election = Election.find(params[:id])

    respond_to do |format|
      if @election.update_attributes(params[:election])
        format.html { redirect_to(@election, :notice => 'Election was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @election.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /elections/1
  # DELETE /elections/1.xml
  def destroy
    @election = Election.find(params[:id])
    @election.destroy

    respond_to do |format|
      format.html { redirect_to(elections_url) }
      format.xml  { head :ok }
    end
  end
end

metrovote/app/helpers/admin/elections_helper.rb
module Admin::ElectionsHelper
end

metrovote/app/helpers/elections_helper.rb
module ElectionsHelper
end

metrovote/app/views/elections/_form.html.haml
=form_for(@election) do |f|
  -if @election.errors.any?
    #error-explanation
      %h2
        = pluralize(@election.errors.count, "error")
        prohibited this election from being saved:
      %ul
        =@election.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    .clearfix
      = f.label :title
      .input
        = f.text_field :title, :placeholder => "Ex: Seattle City Council Elections"
    .clearfix
      = f.label :location
      .input
        = f.text_field :location, :placeholder => "Ex: Seattle, WA"
    .clearfix
      = f.label :keyword
      .input
        = f.text_field :keyword, :placeholder => "Ex: seattle city council"
        %span.help-block A phrase to help find relevant news articles
    .actions
      =f.submit "Save", :class => "btn primary"
      =link_to "Cancel", elections_path, :class => "btn secondary"

metrovote/app/views/elections/index.html.erb
<h1>Listing elections</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Keyword</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @elections.each do |election| %>
  <tr>
    <td><%= election.title %></td>
    <td><%= election.location %></td>
    <td><%= election.keyword %></td>
    <td><%= link_to 'Show', election %></td>
    <td><%= link_to 'Edit', edit_election_path(election) %></td>
    <td><%= link_to 'Destroy', election, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Election', new_election_path %>

metrovote/app/views/elections/show.html.haml
%p#notice
  =notice
.page-header
  %h1= @election.title
%p
  %b Location:
  = @election.location
%p
  %b Keyword:
  = @election.keyword

%h2 Positions
%table
  - @election.positions.each do |position|
    %tr
      %td= position.title
      %td= link_to "Show", position, :class => 'btn primary'
      %td= link_to "Edit", edit_position_path(position), :class => 'btn primary'
= link_to "New position", '/elections/' + @election.id.to_s + '/positions/new', :class => 'btn primary'
%br
= link_to 'Edit', edit_election_path(@election)
= link_to 'Back', elections_path