metrovote/config/routes.rb
Metrovote::Application.routes.draw do

  namespace :admin do
    resources :elections do
      resources :positions do
        resources :candidates
      end
    end
  end

  resources :elections do
    resources :positions do
      resources :candidates
    end
  end

  resources :positions do
    member do
      get 'compare'
    end
  end

  match 'candidates/facebook', :to => 'candidates#facebook'
  match 'candidates/contact-info', :to => 'candidates#contact_info'

  match 'admin', :to => 'admin/elections#index'

  resources :candidates

  root :to => 'positions#index'

end

metrovote/app/models/candidate.rb
require 'twitter'
require 'rbing'

class Candidate < ActiveRecord::Base
  belongs_to :position
  has_many :tweets
  has_many :posts
  has_many :articles

  def get_tweets
    if self.twitter != ""
      Twitter.user_timeline(self.twitter).each do |tweet|
        #created = DateTime.parse(tweet.created_at)
        created = tweet.created_at
        if tweet.in_reply_to_user_id.nil?
          unless Post.exists?(:post_id=>tweet.id, :source=>'twitter', :candidate_id => self.id)

            #get_urls_from_text(tweet.text).each do |url|
              #add_article_by_url(url)
            #end

            @t = Post.new(:message => tweet.text,
                           :source => 'twitter',
                           :picture => tweet.user.profile_image_url,
                           #:name => '',
                           #:caption => '',
                           :icon => tweet.user.profile_image_url,
                           #:type => '',
                           #:description => '',
                           :posted_at => created,
                           :post_id => tweet.id_str,
                           :is_endorsement => has_endorsement(tweet.text),
                           :is_reply => false,
                           :candidate_id => self.id,
                           :from_id => tweet.user.id,
                           :from_name => tweet.user.screen_name)
            @t.save
          end
        end
      end
    end
  end

  def add_article_by_url(url)
    unless url == ''
      logger.debug(url)
      obj = get_link_info(url)
      obj.title
      unless Article.exists?(:url=>obj.url, :candidate_id=>self.id)
        @a = Article.new(:title => obj.title,
                         :snippet => obj.description,
                         :url => obj.url,
                         :date => Time.now,
                         :source => get_source_from_url(obj.url),
                         :candidate_id => self.id)
        @a.save
      end
    end
  end

  def get_fb_posts
    token = "AAADEvdySPLsBAFyCj39cLJFpW8aAAXnr1R5ZCrlZAY2aSlBhrj8BVAGI32TS1eVxEQZC4jZABKZCzyUgZARob2K33YBDxgMVsZD"
    @graph = Koala::Facebook::API.new(token)
    feed = @graph.get_connections(self.class.parse_facebook_url(self.facebook), "feed")
    feed.each do |post|
      created = DateTime.parse(post['created_time'])
      unless Post.exists?(:post_id=>post['id'], :source=>'facebook', :candidate_id => self.id)
        #unless post['link'].nil? or post['link'] == ''
          #add_article_by_url post['link']
        #end

        @p = Post.new(:message => post['message'],
                              :source => 'facebook',
                              :picture => post['picture'],
                              :link => post['link'],
                              :name => post['name'],
                              :caption => post['caption'],
                              :icon => post['icon'],
                              :type => post['type'],
                              :description => post['description'],
                              :posted_at => created,
                              :post_id => post['id'],
                              :is_endorsement => has_endorsement(post['message']),
                              :is_reply => false,
                              :candidate_id => self.id,
                              :from_id => post['from']['id'],
                              :from_name => post['from']['name'])
        @p.save
      end
    end
  end

  def self.get_facebook_info(fb)
    token = "AAADEvdySPLsBAFyCj39cLJFpW8aAAXnr1R5ZCrlZAY2aSlBhrj8BVAGI32TS1eVxEQZC4jZABKZCzyUgZARob2K33YBDxgMVsZD"
    @graph = Koala::Facebook::API.new(token)
    return @graph.get_object(self.parse_facebook_url(fb))
  end

  def get_source_from_url(url)
    uri = URI::parse(url)
    @a = Article.find_by_host(uri.host)
    return @a.source
  end

  def self.parse_facebook_url(url)
    return URI::split(url)[5].split('/')[-1]
  end

  def get_urls_from_text(text)
    p = URI::Parser.new
    return p.extract(text)
  end

  def get_link_info(url)
    embedly_api = Embedly::API.new :key => '27b50eca033711e1b1d14040d3dc5c07',
                                   :caryme => 'Mozilla/5.0 (compatible; metrovote; caryme@gmail.com)'
    obj = embedly_api.oembed :urls => url
    return obj[0]
  end

  def get_articles
    bing = RBing.new("E08C094B36831A4E20810A668B43265D1941F8FE")
    rsp = bing.news(self.name + " " + self.position.election.keyword)
    if rsp.key? 'News'
      rsp.news.results.each do |article|
        created = DateTime.parse(article.Date)
        uri = URI::parse(article.Url)
        logger.debug(article)
        unless Article.exists?(:title=>article.Title, :source => article.Source, :candidate_id=>self.id)
          @a = Article.new(:title => article.Title,
                           :snippet => article.Snippet,
                           :url => article.Url,
                           :date => created,
                           :host => uri.host,
                           :source => article.Source,
                           :candidate_id => self.id)
          @a.save
        end
      end
    end
  end

  def has_endorsement(text)
    return !/endors/i.match(text).nil?
  end

  def fetch_data
    get_articles
    get_tweets
    get_fb_posts
  end

  def feed
    return Post.where("candidate_id=#{self.id} AND message != ''")
  end

  def endorsements
    return Post.where(:candidate_id => self.id, :is_endorsement=>true)
  end

  def self.fetch_tweets
    self.find_each {|c| c.get_tweets}
  end

  def self.fetch_articles
    self.find_each {|a| a.get_articles}
  end

  def self.fetch_fb_posts
    self.find_each {|c| c.get_fb_posts}
  end

  def self.fetch_data
    self.find_each do |candidate|
      candidate.get_articles
      candidate.get_tweets
      candidate.get_fb_posts
    end
  end

end

metrovote/app/controllers/admin/candidates_controller.rb
class Admin::CandidatesController < CandidatesController
  #
  # GET /admin/elections/:election_id/positions/:position_id/candidates/new
  # GET /admin/elections/:election_id/positions/:position_id/candidates/new.xml
  def new
    @election = Election.find(params[:election_id])
    @position = Position.find(params[:position_id])
    @candidate = @position.candidates.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @candidate }
    end
  end

  # POST /candidates
  # POST /candidates.xml
  def create
    @election = Election.find(params[:election_id])
    @position = Position.find(params[:position_id])
    @candidate = @position.candidates.build(params[:candidate])
    logger.debug(@candidate)

    respond_to do |format|
      if @candidate.save
        @candidate.fetch_data
        #format.html { redirect_to(admin_election_position_candidate_path(@candidate), :notice => 'Candidate was successfully created.') }
        # the path above should work. It doesn't. I don't know why. Using below instead
        format.html { redirect_to("/admin/elections/#{@election.id.to_s}/positions/#{@position.id.to_s}", :notice => 'Candidate was successfully created.') }
        format.xml  { render :xml => @candidate, :status => :created, :location => @candidate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @candidate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /candidates
  # GET /candidates.xml
  def index
    @candidates = Candidate.find_all_by_position_id(params[:position_id])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.xml
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @candidate }
    end
  end

  # GET /admin/elections/:election_id/positions/:position_id/candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
    @position = @candidate.position
    @election = @position.election
  end

  # PUT /admin/elections/1/positions/1/candidates/1
  # PUT /admin/elections/1/positions/1/candidates/1.xml
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to(admin_election_position_candidate_path(@candidate), :notice => 'Candidate was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @candidate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/elections/1/positions/1/candidates/1
  # DELETE /admin/elections/1/positions/1/candidates/1.xml
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to(candidates_url) }
      format.xml  { head :ok }
    end
  end


end

metrovote/app/controllers/candidates_controller.rb
require 'open-uri'
require 'cgi'
class CandidatesController < ApplicationController
  # GET /candidates
  # GET /candidates.xml
  def index
    @candidates = Candidate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.xml
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @candidate }
    end
  end

  def facebook
    @c = Candidate.get_facebook_info params[:fb]
    respond_to do |format|
      format.json{ render :json => @c.to_json }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.xml
  def new
    @candidate = Candidate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.xml
  def create
    @candidate = Candidate.new(params[:candidate])

    respond_to do |format|
      if @candidate.save
        @candidate.fetch_data
        format.html { redirect_to(@candidate, :notice => 'Candidate was successfully created.') }
        format.xml  { render :xml => @candidate, :status => :created, :location => @candidate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @candidate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.xml
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to(@candidate, :notice => 'Candidate was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @candidate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.xml
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to(candidates_url) }
      format.xml  { head :ok }
    end
  end

  def get_contact(url)
    @doc = Nokogiri::HTML(open(url))
    @doc.xpath("//a").each do |link|
      matches = /contact/i.match(link.children.text)
      unless matches.nil?
        path = make_absolute(link.attributes['href'].value, url)
        return path
      end
    end
    return nil
  end

  def make_absolute( href, root )
    URI.parse(root).merge(URI.parse(href)).to_s
  end

  def scrape(website)
    doc = Nokogiri::HTML(open(website))
    twitter = ''
    facebook = ''
    doc.css('*[href*=twitter]').each do |link|
      url = link['href']
      logger.debug(link)
      twitter_matches = /twitter.com(\/#!)?\/(\w*)/i.match(url)
      unless twitter_matches.nil?
        twitter = twitter_matches[2]
      end
    end
    doc.css('*[href*=facebook]').each do |link|
      url = link['href']
      if /facebook.com/i.match(url)
        facebook = url
      end
    end
    if facebook == ''
      doc.css('iframe').each do |iframe|
        uri = URI::split(iframe['src'])
        get_params = CGI::parse(uri[7])
        unless get_params['href'].nil?
          facebook = get_params['href']
        end
      end
    end
    phone_matches = /\(?\b([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})\b/i.match(doc)
    if phone_matches.nil?
      phone = ""
    else
      phone = phone_matches[0]
    end
    email_matches = /[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})/i.match(doc)
    if email_matches.nil?
      email = ""
    else
      email = email_matches[0]
    end
    scraped = {:email => email, :phone => phone, :twitter => twitter, :facebook => facebook}
    return scraped
  end

  def fix_http_if_missing(url)
    matches = /http/i.match(url)
    if matches.nil?
      url = "http://" + url
    end
    return url
  end

  def contact_info
    url = fix_http_if_missing params[:url]
    info = scrape(url)
    logger.debug(info)
    phone = info[:phone]
    email = info[:email]
    twitter = info[:twitter]
    facebook = info[:facebook]
    if info[:email].empty? or info[:phone].empty?
      contact_url = get_contact(url)
      unless contact_url.nil?
        backup = scrape(contact_url)
        unless backup[:email].empty?
          email = backup[:email]
        end
        unless backup[:phone].empty?
          phone = backup[:phone]
        end
        unless backup[:twitter].empty?
          twitter = backup[:twitter]
        end
        unless backup[:facebook].empty?
          facebook = backup[:facebook]
        end
      end
    end
    respond_to do |format|
      format.json{ render :json => {:email => email, :phone => phone, :twitter => twitter, :facebook => facebook}.to_json }
    end
  end

end

metrovote/app/helpers/admin/candidates_helper.rb
module Admin::CandidatesHelper
end

metrovote/app/helpers/candidates_helper.rb
module CandidatesHelper
end

metrovote/app/views/candidates/_form.html.haml
= form_for(@candidate) do |f|
  - if @candidate.errors.any?
    #error-explanation
      %h2
        = pluralize(@candidate.errors.count, "error")
        prohibited this candidate from being saved:
      %ul
        =@candidate.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    .clearfix
      = f.label :facebook
      .input
        = f.text_field :facebook
        %button#facebook-fetch.btn Fetch from Facebook
    .clearfix
      = f.label :name
      .input
        = f.text_field :name
    .clearfix
      = f.label :bio
      .input
        = f.text_area :bio
    .clearfix
      = f.label :photo
      .input
        = f.text_field :photo
    .clearfix
      = f.label :website
      .input
        = f.text_field :website
    .clearfix
      = f.label :email
      .input
        = f.text_field :email
    .clearfix
      = f.label :phone
      .input
        = f.text_field :phone
    .clearfix
      = f.label :position_id
      .input
        =f.select(:position_id, Position.all.collect {|p| [p.title, p.id] }, {:include_blank => true})
    .clearfix
      = f.label :twitter
      .input
        = f.text_field :twitter
    .actions
      = f.submit "Save", :class => "btn primary"
      = link_to "Cancel", candidates_path, :class => 'btn secondary' 

metrovote/app/views/candidates/index.html.erb
<h1>Listing candidates</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th>Name</th>
    <th>Bio</th>
    <th>Photo</th>
    <th>Website</th>
    <th>Email</th>
    <th>Position</th>
    <th>Twitter</th>
    <th>Facebook</th>
  </tr>

<% @candidates.each do |candidate| %>
  <tr>
    <td><%= link_to 'Show', candidate %></td>
    <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
    <td><%= link_to 'Destroy', candidate, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= candidate.name %></td>
    <td><%= candidate.bio %></td>
    <td><%= candidate.photo %></td>
    <td><%= candidate.website %></td>
    <td><%= candidate.email %></td>
    <td><%= candidate.position %></td>
    <td><%= candidate.twitter %></td>
    <td><%= candidate.facebook %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Candidate', new_candidate_path %>

metrovote/app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @candidate.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @candidate.bio %>
</p>

<p>
  <b>Photo:</b>
  <%= @candidate.photo %>
</p>

<p>
  <b>Website:</b>
  <%= @candidate.website %>
</p>

<p>
  <b>Email:</b>
  <%= @candidate.email %>
</p>

<p>
  <b>Position:</b>
  <%= @candidate.position %>
</p>

<p>
  <b>Twitter:</b>
  <%= @candidate.twitter %>
</p>

<p>
  <b>Facebook:</b>
  <%= @candidate.facebook %>
</p>

<h3>Tweets</h3>
<table>
  <tr><th>Date</th><th>Tweet</th></tr>
<% @candidate.tweets.each do |c| %>
  <tr>
    <td><%= c.created %></td>
    <td><%= auto_link(c.text).html_safe %></td>
<% end %>
</table>

<h3>Articles</h3>
<table>
  <tr><th>Date</th><th>Title</th><th>URL</th><tr>
<% @candidate.articles.each do |a| %>
  <tr>
    <td><%= a.date %></td>
    <td><%= a.title %></td>
    <td><%= auto_link(a.url).html_safe %></td>
  </tr>
<%end%>
</table>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

metrovote/app/views/candidates/show.html.haml
%p#notice= notice

%p
  %b Name:
  =@candidate.name

%p
  %b Bio:
  =@candidate.bio

%p
  %b Photo:
  =@candidate.photo

%p
  %b Website:
  =@candidate.website

%p
  %b Email:
  =@candidate.email

%p
  %b Position:
  =@candidate.position

%p
  %b Twitter:
  =@candidate.twitter

%p
  %b Facebook:
  =@candidate.facebook

%h3 Tweets
%table
  %tr
    %th Date
    %th Tweet
  - @candidate.tweets.each do |c|
    %tr
      %td= c.created
      %td=auto_link(c.text).html_safe

%h3 Articles
%table
  %tr
    %th Date
    %th Title
    %th URL
  - @candidate.articles.each do |article|
    %tr
      %td= article.date
      %td= article.title
      %td= auto_link(article.url).html_safe
= link_to 'Edit', edit_candidate_path(@candidate)
= link_to 'Back', candidates_path