metrovote/config/routes.rb
Metrovote::Application.routes.draw do

  namespace :admin do
    resources :elections do
      resources :positions do
        resources :candidates
      end
    end
  end

  resources :elections do
    resources :positions do
      resources :candidates
    end
  end

  resources :positions do
    member do
      get 'compare'
    end
  end

  match 'candidates/facebook', :to => 'candidates#facebook'
  match 'candidates/contact-info', :to => 'candidates#contact_info'

  match 'admin', :to => 'admin/elections#index'

  resources :candidates

  root :to => 'positions#index'

end

metrovote/app/models/position.rb
class Position < ActiveRecord::Base
  has_many :candidates
  belongs_to :election

  def articles
    articles = {}
    self.candidates.each do |candidate|
      candidate.articles.each do |article|
        #articles.push article
        key = article.source + article.title
        if articles.has_key? key
          articles[key].candidates.add(candidate)
        else
          #articles[article.url] = {'candidate'=>[candidate], 'article'=>article}
          article.candidates = Set.new [candidate]
          articles[key] = article
        end
      end
    end
    return articles.values.sort {|a,b| b.date <=> a.date }
  end
end

metrovote/app/controllers/admin/positions_controller.rb
class Admin::PositionsController < PositionsController
  def index
    @election = Election.find(params[:election_id])
    @positions = @election.positions

    respond_to do |format|
      format.html
    end
  end

  def show
    @position = Position.find(params[:id])
    @election = Election.find(params[:election_id])
    @candidate1 = @position.candidates[0]
    @candidate2 = @position.candidates[1]
    respond_to do |format|
      format.html
    end
  end

  # GET /elections/:election_id/positions/new
  # GET /elections/:election_id/positions/new.xml
  def new
    @election = Election.find(params[:election_id])
    @position = @election.positions.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @position }
    end
  end

  # POST /positions
  # POST /positions.xml
  def create
    @election = Election.find(params[:election_id])
    @position = @election.positions.build(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to("/admin/elections/#{@election.id.to_s}/positions/#{@position.id.to_s}", :notice => 'Position was successfully created.') }
        format.xml  { render :xml => @position, :status => :created, :location => @position }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @position.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /positions/1/edit
  def edit
    @election = Election.find(params[:election_id])
    @position = Position.find(params[:id])
  end



end

metrovote/app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  # GET /positions
  # GET /positions.xml
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.xml
  def show
    @position = Position.find(params[:id])
    @positions = @position.election.positions
    @candidate1 = @position.candidates[0]
    @candidate2 = @position.candidates[1]
    logger.debug(@candidate1)
    logger.debug(@candidate2)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @position }
    end
  end

  # GET /elections/:election_id/positions/new
  # GET /elections/:election_id/positions/new.xml
  def new
    @election = Election.find(params[:election_id])
    @position = @election.positions.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @position }
    end
  end

  # GET /elections/1/positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.xml
  def create
    @election = Election.find(params[:election_id])
    @position = @election.positions.build(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to(@position, :notice => 'Position was successfully created.') }
        format.xml  { render :xml => @position, :status => :created, :location => @position }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @position.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.xml
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to(@position, :notice => 'Position was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @position.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.xml
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to(positions_url) }
      format.xml  { head :ok }
    end
  end
end

metrovote/app/helpers/admin/positions_helper.rb
module Admin::PositionsHelper
end

metrovote/app/helpers/positions_helper.rb
module PositionsHelper
end

metrovote/app/views/admin/positions/_form.html.haml
= form_for([:admin,@election,@position]) do |f|
  - if @position.errors.any?
    #error-explanation
      %h2
        = pluralize(@position.errors.count, "error")
        prohibited this position from being saved:
      %ul
        - @position.errors.full_messages.each do |msg|
          %li= msg
  .fieldset
    .clearfix
      = f.label :title
      .input
        = f.text_field :title
    .clearfix
      = f.label :region_number
      .input
        = f.text_field :region_number, :class => "span1"
    .clearfix
      = f.label :description
      .input
        = f.text_area :description
  .actions
    = f.submit "Save", :class => 'btn primary'
    =link_to "Cancel", admin_election_positions_path, :class => "btn secondary"

metrovote/app/views/admin/positions/edit.html.haml
%h1 Editing position
= render 'form'
= link_to 'Show', @position

metrovote/app/views/admin/positions/index.html.haml
%table.zebra-striped
  %thead
    %tr
      %th Title
      %th Region number
  - @positions.each do |position|
    %tr
      %td
        =position.title
      %td
        =position.region_number
      %td
        =link_to "Show", "/admin/elections/#{position.election_id.to_s}/positions/#{position.id.to_s}", :class => "btn primary"
      %td
        =link_to "Edit", "/admin/elections/#{position.election_id.to_s}/positions/#{position.id.to_s}/edit", :class => "btn primary"
=link_to "New Position", "/admin/elections/#{@election.id.to_s}/positions/new", :class => "btn primary"

metrovote/app/views/admin/positions/new.html.haml
%h1 New position
= render 'form'

metrovote/app/views/admin/positions/show.html.haml
.page-header
  %h1= @position.title
  =link_to "View site", position_path(@position)


.row
  .span8
    -if @candidate1.nil?
      =link_to "New Candidate", new_admin_election_position_candidate_path(@election, @position), :class => "btn primary"
    -else
      %h2= @candidate1.name
      %img{:src => @candidate1.photo}
      %p= @candidate1.bio
  .span8
    -if @candidate2.nil?
      =link_to "New Candidate", new_admin_election_position_candidate_path(@election, @position), :class => "btn primary"
    -else
      %h2= @candidate2.name
      %img{:src => @candidate2.photo}
      %p= @candidate2.bio
.row
  .span8
    -unless @candidate1.nil?
      %table
        %tr
          %th Website
          %td= @candidate1.website
        %tr
          %th Twitter
          %td= @candidate1.twitter
        %tr
          %th Facebook
          %td= @candidate1.facebook
        %tr
          %th Phone
          %td= @candidate1.phone
        %tr
          %th Email
          %td= @candidate1.email
        %tr
          %th Is incumbent
          %td= @candidate1.is_incumbent.to_s
      =link_to "Edit Candidate", edit_admin_election_position_candidate_path(@election, @position, @candidate1), :class => "btn primary"
  .span8
    -unless @candidate2.nil?
      %table
        %tr
          %th Website
          %td= @candidate2.website
        %tr
          %th Twitter
          %td= @candidate2.twitter
        %tr
          %th Facebook
          %td= @candidate2.facebook
        %tr
          %th Phone
          %td= @candidate2.phone
        %tr
          %th Email
          %td= @candidate2.email
        %tr
          %th Is incumbent
          %td= @candidate2.is_incumbent.to_s
      =link_to "Edit Candidate", edit_admin_election_position_candidate_path(@election, @position, @candidate2), :class => "btn primary"